Add babel plugins for optimization
rispa-io/rispa-client pull request #7
Opened 2017-06-22 13:02 UTC by wuzyk

- constant-elements
- inline-elements
- remove-prop-types

2017-06-22 13:40 UTC, wuzyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [35 Оптимизация сборки клиентского бандла вебпаком](https://trello.com/c/JJEjgx20/35-35-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%B1%D0%B0%D0%BD%D0%B4%D0%BB%D0%B0-%D0%B2%D0%B5%D0%B1%D0%BF%D0%B0%D0%BA%D0%BE%D0%BC)

2017-06-23 07:51 UTC, Laiff requested changes

2017-06-23 07:51 UTC, Laiff commented on .rispa/babel-options.js
> +    ...(isProd ? productionPlugins : []),
Технически можно задавать окружение еще через BABEL_ENV лучше ориентироваться на разрешение бабелем этого, то есть передавать ключи 'development' 'production'

2017-06-23 14:33 UTC, Laiff approved these changes

2017-06-23 14:37 UTC, Laiff commented
@wuzyk разрули конфликты

2017-06-23 15:39 UTC, Laiff approved these changes

2017-06-23 15:39 UTC, merged