Add support for offline mode
rispa-io/rispa-client pull request #9
Opened 2017-06-23 12:01 UTC by wuzyk

2017-06-23 12:03 UTC, wuzyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [33 Добавление offline режима в клиентский плагин](https://trello.com/c/xU6iJS3k/33-33-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-offline-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0-%D0%B2-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD)

2017-06-23 14:28 UTC, Laiff requested changes

2017-06-23 14:28 UTC, Laiff commented on package.json
> +    "webpack": "^2.4.1",
Для чего тут зависимость от webpack?

2017-06-23 14:30 UTC, wuzyk commented on package.json
> +    "webpack": "^2.4.1",
offline-plugin использует какие-то либы вебпака

2017-06-23 14:33 UTC, wuzyk commented on package.json
> +    "webpack": "^2.4.1",
https://github.com/NekR/offline-plugin/blob/master/src/service-worker.js#L3

2017-06-23 14:41 UTC, Laiff commented on package.json
> +    "webpack": "^2.4.1",
Чую я нам это еще аукнется, ладно ок

2017-06-23 14:41 UTC, Laiff commented
Конфликты

2017-06-23 14:41 UTC, Laiff approved these changes

2017-06-26 06:53 UTC, Laiff approved these changes

2017-06-26 06:54 UTC, merged